version: '3.9'

services:
  finebi:
    # build: .
    image: ddmitry80/finebi:6.1.0.01-centos
    container_name: finebi
    environment:
      - TZ=Europe/Moscow
    ports:
      - "37799:37799"
    volumes:
      - data:/usr/local/FineBI6.1/webapps/webroot
    tty: true
    restart: unless-stopped

  finedb:
    image: mysql:5.7-debian
    container_name: finedb
    environment:
      - TZ=Europe/Moscow
    volumes:
      - db-data:/var/lib/mysql
    command: --character-set-server=utf8 --collation-server=utf8_bin
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: finedb
      MYSQL_USER: finebi
      MYSQL_PASSWORD: finebi
    ports:
      - "37798:3306"
    restart: unless-stopped

volumes:
  data:
  db-data: